python testScipt5.py > testScipt5.py.txt
python testScipt6.py > testScipt6.py.txt
python testScipt7.py > testScipt7.py.txt
python kerasMain2.py > kerasMain2.py.txt
python kerasMain3.py > kerasMain3.py.txt
python kerasMain4.py > kerasMain4.py.txt
python kerasMainLSTM.py > kerasMainLSTM.py.txt
python kerasMainLSTM2.py > kerasMainLSTM2.py.txt
python kerasMainLSTM3.py > kerasMainLSTM3.py.txt
